# Generated by Django 5.1.3 on 2024-11-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('nacimiento', models.DateField()),
                ('titulo', models.CharField(max_length=250)),
                ('cv', models.FileField(upload_to='curriculums')),
                ('sobre_mi', models.TextField()),
            ],
        ),
    ]
